apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: battlefields.rhte.demojam.battlefield
spec:
  group: rhte.demojam.battlefield
  names:
    kind: Battlefield
    listKind: BattlefieldList
    plural: battlefields
    singular: battlefield
    shortNames:
    - bf
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            duration:
              format: int64
              type: integer
            hitFrequency:
              format: int64
              type: integer
            players:
              items:
                properties:
                  image:
                    type: string
                  maxhealth:
                    format: int64
                    type: integer
                  name:
                    type: string
                required:
                - name
                - maxhealth
                type: object
              type: array
          required:
          - duration
          - players
          - hitFrequency
          type: object
        status:
          properties:
            phase:
              type: string
            scores:
              items:
                properties:
                  death:
                    format: int64
                    type: integer
                  kill:
                    format: int64
                    type: integer
                  name:
                    type: string
                required:
                - name
                - kill
                - death
                type: object
              type: array
            startTime:
              format: date-time
              type: string
            stopTime:
              format: date-time
              type: string
          required:
          - phase
          - scores
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
